# Generated by Django 3.0.6 on 2022-04-02 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220402_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postrate',
            old_name='created_on',
            new_name='rate_date',
        ),
    ]
