# Generated by Django 3.0.6 on 2022-04-02 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220402_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='in_reply_to_post',
        ),
    ]
