# Generated by Django 3.0.6 on 2022-04-03 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_useractivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='activity_time',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 3, 15, 12, 9, 447143)),
        ),
    ]
